"""final change

Revision ID: 486ccd3d3bf2
Revises: 98eeebbfa276
Create Date: 2024-02-13 19:36:57.852084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486ccd3d3bf2'
down_revision = '98eeebbfa276'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
