"""done done 

Revision ID: 71e498d85c71
Revises: e7820bd68561
Create Date: 2024-02-13 22:31:39.513064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e498d85c71'
down_revision = 'e7820bd68561'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
