"""Add game_user Association Table

Revision ID: 76e3fd42e44d
Revises: 6b7d21321e46
Create Date: 2024-02-13 15:12:28.623058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e3fd42e44d'
down_revision = '6b7d21321e46'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
