"""Added star rating Column

Revision ID: 8a8c441677ac
Revises: c7fea5b8ecb9
Create Date: 2024-02-13 05:46:48.908391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a8c441677ac'
down_revision = 'c7fea5b8ecb9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('star_rating', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'star_rating')
    # ### end Alembic commands ###
