"""updated instance methods

Revision ID: 8da938fdc741
Revises: 76e3fd42e44d
Create Date: 2024-02-13 15:45:13.586913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da938fdc741'
down_revision = '76e3fd42e44d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
