"""done

Revision ID: 976753033d62
Revises: 486ccd3d3bf2
Create Date: 2024-02-13 21:56:37.845927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976753033d62'
down_revision = '486ccd3d3bf2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
