"""updated model

Revision ID: 98eeebbfa276
Revises: 8da938fdc741
Create Date: 2024-02-13 15:54:27.186765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98eeebbfa276'
down_revision = '8da938fdc741'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
